export const TODO_LIST_REQUEST = 'TODO_LIST_REQUEST';
export const TODO_LIST_SUCCESS = 'TODO_LIST_SUCCESS';
export const TODO_LIST_FAIL = 'TODO_LIST_FAIL'; 

export const TODO_EDIT_REQUEST = 'TODO_EDIT_REQUEST';
export const TODO_EDIT_SUCCESS = 'TODO_EDIT_SUCCESS';
export const TODO_EDIT_FAIL = 'TODO_EDIT_FAIL'; 

export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_FAIL = 'TODO_DELETE_FAIL'; 

export const TODO_POST_REQUEST = 'TODO_POST_REQUEST';
export const TODO_POST_SUCCESS = 'TODO_POST_SUCCESS';
export const TODO_POST_FAIL = 'TODO_POST_FAIL'; 
export const TODO_POST_RESET = 'TODO_POST_RESET'; 

export const TODO_FILTER_SUCCESS = 'TODO_FILTER_SUCCESS';
export const TODO_FILTER_FAIL = 'TODO_FILTER_FAIL'; 
